<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="27" passed="22">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="300604" started-at="2018-03-05T10:55:19Z" finished-at="2018-03-05T11:00:20Z">
    <groups>
      <group name="Critical">
        <method signature="ReportsSiute.ERT_SUMM_16_Verify_ERTColumn()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_16_Verify_ERTColumn" class="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute"/>
      </group> <!-- Critical -->
    </groups>
    <test name="Default test" duration-ms="300604" started-at="2018-03-05T10:55:19Z" finished-at="2018-03-05T11:00:20Z">
      <class name="com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute">
        <test-method status="PASS" signature="loadlog4j()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="loadlog4j" is-config="true" duration-ms="47" started-at="2018-03-05T16:25:19Z" finished-at="2018-03-05T16:25:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadlog4j -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeClass" is-config="true" duration-ms="19555" started-at="2018-03-05T16:25:19Z" finished-at="2018-03-05T16:25:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="5" started-at="2018-03-05T16:25:39Z" finished-at="2018-03-05T16:25:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_01_Verify_HomePage() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_01_Verify_HomePage()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_01_Verify_HomePage" duration-ms="120642" started-at="2018-03-05T16:25:39Z" finished-at="2018-03-05T16:27:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_01_Verify_HomePage -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:27:39Z" finished-at="2018-03-05T16:27:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_02_Verify_the_Reports_menu_on_top_bar()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_02_Verify_the_Reports_menu_on_top_bar()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_02_Verify_the_Reports_menu_on_top_bar" duration-ms="7671" started-at="2018-03-05T16:27:39Z" finished-at="2018-03-05T16:27:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_02_Verify_the_Reports_menu_on_top_bar -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:27:39Z" finished-at="2018-03-05T16:27:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_01_Verify_HomePage status=SUCCESS method=ReportsSiute.ERT_SUMM_01_Verify_HomePage()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:27:47Z" finished-at="2018-03-05T16:27:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_02_Verify_the_Reports_menu_on_top_bar status=SUCCESS method=ReportsSiute.ERT_SUMM_02_Verify_the_Reports_menu_on_top_bar()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-03-05T16:27:47Z" finished-at="2018-03-05T16:27:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_03_Verify_the_ERT_summary_report_page()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_03_Verify_the_ERT_summary_report_page()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_03_Verify_the_ERT_summary_report_page" duration-ms="2" started-at="2018-03-05T16:27:47Z" description="DateFilter, ClientFilter, SessionFilters are Available" finished-at="2018-03-05T16:27:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_03_Verify_the_ERT_summary_report_page -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:27:47Z" finished-at="2018-03-05T16:27:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_03_Verify_the_ERT_summary_report_page status=SUCCESS method=ReportsSiute.ERT_SUMM_03_Verify_the_ERT_summary_report_page()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:27:47Z" finished-at="2018-03-05T16:27:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_04_Verify_DateEntry_Manually() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_04_Verify_DateEntry_Manually()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_04_Verify_DateEntry_Manually" duration-ms="15307" started-at="2018-03-05T16:27:47Z" finished-at="2018-03-05T16:28:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_04_Verify_DateEntry_Manually -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:28:02Z" finished-at="2018-03-05T16:28:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_04_Verify_DateEntry_Manually status=SUCCESS method=ReportsSiute.ERT_SUMM_04_Verify_DateEntry_Manually()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-03-05T16:28:02Z" finished-at="2018-03-05T16:28:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_05_Verify_DateFiter_For_FutureDates() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_05_Verify_DateFiter_For_FutureDates()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_05_Verify_DateFiter_For_FutureDates" duration-ms="1281" started-at="2018-03-05T16:28:02Z" finished-at="2018-03-05T16:28:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_05_Verify_DateFiter_For_FutureDates -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-05T16:28:04Z" finished-at="2018-03-05T16:28:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_05_Verify_DateFiter_For_FutureDates status=SUCCESS method=ReportsSiute.ERT_SUMM_05_Verify_DateFiter_For_FutureDates()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_06_Verify_DateFiter_For_Morethan_90days()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_06_Verify_DateFiter_For_Morethan_90days" duration-ms="91105" started-at="2018-03-05T16:28:04Z" finished-at="2018-03-05T16:29:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_06_Verify_DateFiter_For_Morethan_90days -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:28:04Z" finished-at="2018-03-05T16:28:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_06_Verify_DateFiter_For_Morethan_90days() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-03-05T16:29:35Z" finished-at="2018-03-05T16:29:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_07_Verify_ClientFilter() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:29:35Z" finished-at="2018-03-05T16:29:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_06_Verify_DateFiter_For_Morethan_90days status=SUCCESS method=ReportsSiute.ERT_SUMM_06_Verify_DateFiter_For_Morethan_90days()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_07_Verify_ClientFilter()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_07_Verify_ClientFilter" duration-ms="163" started-at="2018-03-05T16:29:35Z" finished-at="2018-03-05T16:29:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_07_Verify_ClientFilter -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:29:35Z" finished-at="2018-03-05T16:29:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_07_Verify_ClientFilter status=SUCCESS method=ReportsSiute.ERT_SUMM_07_Verify_ClientFilter()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_08_Verify_SessionFilter()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_08_Verify_SessionFilter" duration-ms="3728" started-at="2018-03-05T16:29:35Z" finished-at="2018-03-05T16:29:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_08_Verify_SessionFilter -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:29:35Z" finished-at="2018-03-05T16:29:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_08_Verify_SessionFilter() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:29:39Z" finished-at="2018-03-05T16:29:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_08_Verify_SessionFilter status=SUCCESS method=ReportsSiute.ERT_SUMM_08_Verify_SessionFilter()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="ERT_SUMM_09_Verify_ReportTitle()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_09_Verify_ReportTitle" duration-ms="113" started-at="2018-03-05T16:29:39Z" finished-at="2018-03-05T16:29:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Does Not Match expected [ERT ACTION REPORT SUMMARY OF RCR MUTHOOT KOCHI - RCR REGION ON 18 DEC 2017 Morning ERT] but found [2018-03-05 Morning ERT]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Does Not Match expected [ERT ACTION REPORT SUMMARY OF RCR MUTHOOT KOCHI - RCR REGION ON 18 DEC 2017 Morning ERT] but found [2018-03-05 Morning ERT]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.Cogniphy.Protection.Muthoot.Reports.ERTSummay_Report.verifyReportTitle(ERTSummay_Report.java:44)
	at com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_09_Verify_ReportTitle(ReportsSiute.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_09_Verify_ReportTitle -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:29:39Z" finished-at="2018-03-05T16:29:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_09_Verify_ReportTitle() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="675" started-at="2018-03-05T16:29:39Z" finished-at="2018-03-05T16:29:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_09_Verify_ReportTitle status=FAILURE method=ReportsSiute.ERT_SUMM_09_Verify_ReportTitle()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:29:40Z" finished-at="2018-03-05T16:29:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_10_Verify_TitleRow() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_10_Verify_TitleRow()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_10_Verify_TitleRow" duration-ms="620" started-at="2018-03-05T16:29:40Z" finished-at="2018-03-05T16:29:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_10_Verify_TitleRow -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-03-05T16:29:40Z" finished-at="2018-03-05T16:29:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_16_Verify_ERTColumn() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:29:40Z" finished-at="2018-03-05T16:29:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_10_Verify_TitleRow status=SUCCESS method=ReportsSiute.ERT_SUMM_10_Verify_TitleRow()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="ERT_SUMM_16_Verify_ERTColumn()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_16_Verify_ERTColumn" duration-ms="28939" started-at="2018-03-05T16:29:40Z" finished-at="2018-03-05T16:30:09Z">
          <exception class="org.openqa.selenium.StaleElementReferenceException">
            <message>
              <![CDATA[stale element reference: element is not attached to the page document
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'USER', ip: '192.168.2.109', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.33.506120 (e3e53437346286..., userDataDir: C:\Users\121\AppData\Local\...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 64.0.3282.186, webStorageEnabled: true}
Session ID: 8dbba936c255816e9b354797745ed300]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'USER', ip: '192.168.2.109', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.33.506120 (e3e53437346286..., userDataDir: C:\Users\121\AppData\Local\...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 64.0.3282.186, webStorageEnabled: true}
Session ID: 8dbba936c255816e9b354797745ed300
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:160)
	at com.Cogniphy.Protection.Muthoot.Reports.ERTSummay_Report.namesFrom_Application(ERTSummay_Report.java:380)
	at com.Cogniphy.Protection.Muthoot.Reports.ERTSummay_Report.verifyAll_ERTs(ERTSummay_Report.java:388)
	at com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_16_Verify_ERTColumn(ReportsSiute.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.StaleElementReferenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_16_Verify_ERTColumn -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="348" started-at="2018-03-05T16:30:09Z" finished-at="2018-03-05T16:30:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_16_Verify_ERTColumn status=FAILURE method=ReportsSiute.ERT_SUMM_16_Verify_ERTColumn()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-03-05T16:30:09Z" finished-at="2018-03-05T16:30:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_17_Validate_ERT_count() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_17_Validate_ERT_count()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_17_Validate_ERT_count" duration-ms="2" started-at="2018-03-05T16:30:09Z" description="Bug has to be fix" finished-at="2018-03-05T16:30:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_17_Validate_ERT_count -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-03-05T16:30:09Z" finished-at="2018-03-05T16:30:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_18_Verify_ReportAt_TimeFormat() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:09Z" finished-at="2018-03-05T16:30:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_17_Validate_ERT_count status=SUCCESS method=ReportsSiute.ERT_SUMM_17_Validate_ERT_count()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_18_Verify_ReportAt_TimeFormat()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_18_Verify_ReportAt_TimeFormat" duration-ms="1401" started-at="2018-03-05T16:30:09Z" finished-at="2018-03-05T16:30:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_18_Verify_ReportAt_TimeFormat -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-05T16:30:11Z" finished-at="2018-03-05T16:30:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_18_Verify_ReportAt_TimeFormat status=SUCCESS method=ReportsSiute.ERT_SUMM_18_Verify_ReportAt_TimeFormat()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_19_Validate_the_ERT_Reported_AT_Column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_19_Validate_the_ERT_Reported_AT_Column" duration-ms="54" started-at="2018-03-05T16:30:11Z" finished-at="2018-03-05T16:30:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_19_Validate_the_ERT_Reported_AT_Column -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:11Z" finished-at="2018-03-05T16:30:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_19_Validate_the_ERT_Reported_AT_Column() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:11Z" finished-at="2018-03-05T16:30:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_19_Validate_the_ERT_Reported_AT_Column status=SUCCESS method=ReportsSiute.ERT_SUMM_19_Validate_the_ERT_Reported_AT_Column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:11Z" finished-at="2018-03-05T16:30:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_20_Validate_ReportAt_with_GaurdCheckList_ReportTime() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:11Z" finished-at="2018-03-05T16:30:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_21_22_Validate_No_of_the_branches_visited_column() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_21_22_Validate_No_of_the_branches_visited_column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_21_22_Validate_No_of_the_branches_visited_column" duration-ms="4479" started-at="2018-03-05T16:30:11Z" finished-at="2018-03-05T16:30:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_21_22_Validate_No_of_the_branches_visited_column -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:11Z" finished-at="2018-03-05T16:30:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_20_Validate_ReportAt_with_GaurdCheckList_ReportTime status=SUCCESS method=ReportsSiute.ERT_SUMM_20_Validate_ReportAt_with_GaurdCheckList_ReportTime()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_20_Validate_ReportAt_with_GaurdCheckList_ReportTime()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_20_Validate_ReportAt_with_GaurdCheckList_ReportTime" duration-ms="0" started-at="2018-03-05T16:30:11Z" description="Bug has to be fix" finished-at="2018-03-05T16:30:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_20_Validate_ReportAt_with_GaurdCheckList_ReportTime -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:15Z" finished-at="2018-03-05T16:30:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_21_22_Validate_No_of_the_branches_visited_column status=SUCCESS method=ReportsSiute.ERT_SUMM_21_22_Validate_No_of_the_branches_visited_column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:15Z" finished-at="2018-03-05T16:30:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_27_Validate_ADTRecived_Time() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_27_Validate_ADTRecived_Time()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_27_Validate_ADTRecived_Time" duration-ms="16" started-at="2018-03-05T16:30:15Z" finished-at="2018-03-05T16:30:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_27_Validate_ADTRecived_Time -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:15Z" finished-at="2018-03-05T16:30:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_31_Verify_timeOf_Arrival_At_destination() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_31_Verify_timeOf_Arrival_At_destination()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_31_Verify_timeOf_Arrival_At_destination" duration-ms="94" started-at="2018-03-05T16:30:15Z" finished-at="2018-03-05T16:30:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_31_Verify_timeOf_Arrival_At_destination -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:15Z" finished-at="2018-03-05T16:30:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_27_Validate_ADTRecived_Time status=SUCCESS method=ReportsSiute.ERT_SUMM_27_Validate_ADTRecived_Time()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:16Z" finished-at="2018-03-05T16:30:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_32_Verify_Total_responding_Time() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:16Z" finished-at="2018-03-05T16:30:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_31_Verify_timeOf_Arrival_At_destination status=SUCCESS method=ReportsSiute.ERT_SUMM_31_Verify_timeOf_Arrival_At_destination()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_32_Verify_Total_responding_Time()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_32_Verify_Total_responding_Time" duration-ms="109" started-at="2018-03-05T16:30:16Z" finished-at="2018-03-05T16:30:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_32_Verify_Total_responding_Time -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:16Z" finished-at="2018-03-05T16:30:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_32_Verify_Total_responding_Time status=SUCCESS method=ReportsSiute.ERT_SUMM_32_Verify_Total_responding_Time()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="ERT_SUMM_33_34_Verify_KM_coveredIn_ADT()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_33_34_Verify_KM_coveredIn_ADT" duration-ms="31" started-at="2018-03-05T16:30:16Z" finished-at="2018-03-05T16:30:16Z">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: ""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.Cogniphy.Protection.Muthoot.Reports.ERTSummay_Report.verifyKMCovered(ERTSummay_Report.java:128)
	at com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_33_34_Verify_KM_coveredIn_ADT(ReportsSiute.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_33_34_Verify_KM_coveredIn_ADT -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:16Z" finished-at="2018-03-05T16:30:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_33_34_Verify_KM_coveredIn_ADT() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="359" started-at="2018-03-05T16:30:16Z" finished-at="2018-03-05T16:30:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_33_34_Verify_KM_coveredIn_ADT status=FAILURE method=ReportsSiute.ERT_SUMM_33_34_Verify_KM_coveredIn_ADT()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:16Z" finished-at="2018-03-05T16:30:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_35_Validate_Total_KM_run_by_ERT() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="ERT_SUMM_35_Validate_Total_KM_run_by_ERT()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_35_Validate_Total_KM_run_by_ERT" duration-ms="497" started-at="2018-03-05T16:30:16Z" finished-at="2018-03-05T16:30:17Z">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: ""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.Cogniphy.Protection.Muthoot.Reports.ERTSummay_Report.validateKMsRunByVehicles(ERTSummay_Report.java:299)
	at com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_35_Validate_Total_KM_run_by_ERT(ReportsSiute.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_35_Validate_Total_KM_run_by_ERT -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="316" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_35_Validate_Total_KM_run_by_ERT status=FAILURE method=ReportsSiute.ERT_SUMM_35_Validate_Total_KM_run_by_ERT()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_37_38_Validate_the_ERT_Relieving_Time_column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_37_38_Validate_the_ERT_Relieving_Time_column" duration-ms="125" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_37_38_Validate_the_ERT_Relieving_Time_column -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_37_38_Validate_the_ERT_Relieving_Time_column() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_37_38_Validate_the_ERT_Relieving_Time_column status=SUCCESS method=ReportsSiute.ERT_SUMM_37_38_Validate_the_ERT_Relieving_Time_column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_39_Verify_the_Irregularities_column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_39_Verify_the_Irregularities_column" duration-ms="132" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_39_Verify_the_Irregularities_column -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_39_Verify_the_Irregularities_column() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="ERT_SUMM_40_Verify_Action_taken_by_ERT_and_RCR_Column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_40_Verify_Action_taken_by_ERT_and_RCR_Column" duration-ms="183" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_40_Verify_Action_taken_by_ERT_and_RCR_Column -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_40_Verify_Action_taken_by_ERT_and_RCR_Column() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_39_Verify_the_Irregularities_column status=SUCCESS method=ReportsSiute.ERT_SUMM_39_Verify_the_Irregularities_column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_40_Verify_Action_taken_by_ERT_and_RCR_Column status=SUCCESS method=ReportsSiute.ERT_SUMM_40_Verify_Action_taken_by_ERT_and_RCR_Column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_41_42_Verify_Action_taken_by_ERT_and_RCR_Column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_41_42_Verify_Action_taken_by_ERT_and_RCR_Column" duration-ms="156" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_41_42_Verify_Action_taken_by_ERT_and_RCR_Column -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_41_42_Verify_Action_taken_by_ERT_and_RCR_Column() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_43_44_45_Validate_odometer_Values() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_41_42_Verify_Action_taken_by_ERT_and_RCR_Column status=SUCCESS method=ReportsSiute.ERT_SUMM_41_42_Verify_Action_taken_by_ERT_and_RCR_Column()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="ERT_SUMM_43_44_45_Validate_odometer_Values()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_43_44_45_Validate_odometer_Values" duration-ms="360" started-at="2018-03-05T16:30:17Z" finished-at="2018-03-05T16:30:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_43_44_45_Validate_odometer_Values -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:18Z" finished-at="2018-03-05T16:30:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_46_Validate_total_Count() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-05T16:30:18Z" finished-at="2018-03-05T16:30:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_43_44_45_Validate_odometer_Values status=SUCCESS method=ReportsSiute.ERT_SUMM_43_44_45_Validate_odometer_Values()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="ERT_SUMM_46_Validate_total_Count()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="ERT_SUMM_46_Validate_total_Count" duration-ms="0" started-at="2018-03-05T16:30:18Z" finished-at="2018-03-05T16:30:18Z">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: ""]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute.ERT_SUMM_46_Validate_total_Count(ReportsSiute.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ERT_SUMM_46_Validate_total_Count -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterMethod" is-config="true" duration-ms="264" started-at="2018-03-05T16:30:18Z" finished-at="2018-03-05T16:30:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ERT_SUMM_46_Validate_total_Count status=FAILURE method=ReportsSiute.ERT_SUMM_46_Validate_total_Count()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="toEndTest()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="toEndTest" is-config="true" duration-ms="875" started-at="2018-03-05T16:30:18Z" finished-at="2018-03-05T16:30:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- toEndTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute@44c8afef]" name="afterTest" is-config="true" duration-ms="849" started-at="2018-03-05T16:30:19Z" finished-at="2018-03-05T16:30:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.Cogniphy.Protection.Muthoot.TestSuites.ReportsSiute -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
